"""Added User model with password hashing

Revision ID: 59de93057714
Revises: 9712b483e3c8
Create Date: 2024-10-07 16:49:48.486122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59de93057714'
down_revision = '9712b483e3c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
